### ISSUE TITLE
stackoverflow when using 0.2.2 version

### ISSUE THREAD

**Issue by demetthyl** [xebialabs-community/gradle-xld-plugin#7] opened 2016-03-03 09:33 UTC
Hello,

we encounter an issue while using the 0.2.2 version of the gradle plugin :
`17:24:15.010 [ERROR] [org.gradle.BuildExceptionReporter]        at com.xebialabs.gradle.xldeploy.DarTask.copy(DarTask.groovy:54)
17:24:15.011 [ERROR] [org.gradle.BuildExceptionReporter]        at com.xebialabs.gradle.xldeploy.DarTask.copy(DarTask.groovy:54)
17:24:15.011 [ERROR] [org.gradle.BuildExceptionReporter]        at com.xebialabs.gradle.xldeploy.DarTask.copy(DarTask.groovy:54)
17:24:15.011 [ERROR] [org.gradle.BuildExceptionReporter]        at com.xebialabs.gradle.xldeploy.DarTask.copy(DarTask.groovy:54)
17:24:15.011 [ERROR] [org.gradle.BuildExceptionReporter]        at com.xebialabs.gradle.xldeploy.DarTask.copy(DarTask.groovy:54)
`

i tried to use -d and --stacktrace, but i can't get more informations.

Command used : gradle jar deploy
gradle version : 2.11

src/main/dar/manifest.xml content :+1: 
`<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage version="12" application="DPY/${project.name}">
  <deployables>
      <file.File name="testPackage" file="${artifact(project.jar)}">
      <targetPath>/tmp/</targetPath>
  </file.File>
  </deployables>
</udm.DeploymentPackage>`

Regards,
Guillaume

**Comment by byaminov** [comment] 2016-03-03 20:25
Hi @demetthyl confirmed the bug, thanks for reporting. It's happening since Gradle 2.8. I'll create a fix.

**Comment by byaminov** [comment] 2016-03-03 20:41
@demetthyl I released [version 0.2.3](https://plugins.gradle.org/plugin/com.xebialabs.xl-deploy/0.2.3) of the plugin with the fix for this issue. Please check if it works for you.

**Comment by demetthyl** [comment] 2016-03-04 14:11
@byaminov thank you very much : i did multiple tests and upgraded to java8, all is ok.

Regards,
Guillaume

**Comment by byaminov** [comment] 2016-03-04 14:34
Great, then I close this issue.

**Closed as completed by byaminov** 2016-03-04 14:34 UTC
